// Dummy data translated from lib/data/local/preloaded_data.dart
// Will be inserted into MongoDB via seed.js with generated ObjectIds

const seedData = {
  albums: [
    {
      title: "Rawang Echoes of the Mountains",
      ownerType: "singer",
      ownerName: "Ah Dang Rawang",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 2023,
      description: "Soulful vocal ballads preserving ancient Rawang poetry and acoustic acoustic guitar.",
      trackCount: 4,
    },
    {
      title: "Golden Highland Melodies",
      ownerType: "singer",
      ownerName: "Seng Rawang",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 2024,
      description: "Celebrated modern and folk songs reflecting love for the Northern mountains.",
      trackCount: 3,
    },
    {
      title: "Rawang Heritage Archive Vol. 1",
      ownerType: "organization",
      ownerName: "Rawang Literature & Culture Association",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 2021,
      description: "Official cultural field recordings of ritual chants, festivals, and folk lore.",
      trackCount: 4,
    },
    {
      title: "Northern Valley Choral Hymns",
      ownerType: "organization",
      ownerName: "Rawang Youth Heritage Choir",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 2022,
      description: "Harmonious polyphonic choral singing in traditional Rawang dialects.",
      trackCount: 3,
    },
    {
      title: "Ancient River Chants & Rituals",
      ownerType: "anonymous",
      ownerName: "Anonymous Collection",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 1998,
      description: "Traditional ancestral chants recorded across generations without individual author attribution.",
      trackCount: 3,
    },
    {
      title: "Bamboo Harp & Flute Solos",
      ownerType: "anonymous",
      ownerName: "Anonymous Collection",
      coverResName: "img_rawang_hero_1785383680261",
      releaseYear: 2005,
      description: "Soothing instrumental bamboo flute (Pung-lu) and mouth harp melodies.",
      trackCount: 3,
    },
    { title: "John's Acoustic Hits", ownerType: "singer", ownerName: "John Singer", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2023, description: "Dummy album", trackCount: 1 },
    { title: "Maria's Folk Songs", ownerType: "singer", ownerName: "Maria Artist", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2022, description: "Dummy album", trackCount: 1 },
    { title: "David Unplugged", ownerType: "singer", ownerName: "David Vocals", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2021, description: "Dummy album", trackCount: 1 },
    { title: "Sarah's Classic Melodies", ownerType: "singer", ownerName: "Sarah Melody", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2024, description: "Dummy album", trackCount: 1 },
    { title: "Peter's Evening Tunes", ownerType: "singer", ownerName: "Peter Tune", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2023, description: "Dummy album", trackCount: 1 },
    { title: "Traditional Arts Compilation", ownerType: "organization", ownerName: "Traditional Arts Org", coverResName: "img_rawang_hero_1785383680261", releaseYear: 2020, description: "Dummy album", trackCount: 1 },
  ],

  tracksWithAlbumRef: [
    // Album 1 (Singer: Ah Dang Rawang) — index 0
    {
      albumIndex: 0,
      title: "Pungye Harvest Song",
      rawangTitle: "Pungye Lagung Rung",
      artistName: "Ah Dang Rawang",
      albumName: "Rawang Echoes of the Mountains",
      ownerType: "singer",
      durationSeconds: 215,
      audioUrl: "synth:440:600",
      lyrics: "[Rawang]\nPungye lagung, pangsi zong,\nKadu mu mado, goli so.\nRawang ka ring, zi mu ma,\nAba amya, nung kamo.\n\n[English Translation]\nWhen the golden harvest ripens in the valley,\nWe gather under the eternal snow peaks.\nPreserve our heritage with pride,\nFor future generations to hear our song.",
      genre: "Traditional Folk Ballad",
      hasKaraoke: true,
      karaokeAudioUrl: "synth:karaoke:440:600",
    },
    {
      albumIndex: 0,
      title: "Mali River Sunset",
      rawangTitle: "Mali Hka Wang",
      artistName: "Ah Dang Rawang",
      albumName: "Rawang Echoes of the Mountains",
      ownerType: "singer",
      durationSeconds: 198,
      audioUrl: "synth:380:520",
      lyrics: "[Rawang]\nMali hka ring, so zong pe,\nGoli so chyu, Rawang ka.\n\n[English Translation]\nBeside the clear Mali Hka river streams,\nWe sing of peace and homeland.",
      genre: "Acoustic Ballad",
      hasKaraoke: true,
      karaokeAudioUrl: "synth:karaoke:380:520",
    },
    {
      albumIndex: 0,
      title: "Snow Peak Longing",
      rawangTitle: "Hkakabo Razi So",
      artistName: "Ah Dang Rawang",
      albumName: "Rawang Echoes of the Mountains",
      ownerType: "singer",
      durationSeconds: 240,
      audioUrl: "synth:320:440",
      lyrics: "[Rawang]\nHkakabo razi, zi goli,\nRawang pong ka, mu so.\n\n[English Translation]\nLooking towards Hkakabo Razi mountain,\nOur heart remains steadfast in tradition.",
      genre: "Acoustic Folk",
    },
    {
      albumIndex: 0,
      title: "Mother's Lullaby",
      rawangTitle: "Anu So Lagung",
      artistName: "Ah Dang Rawang",
      albumName: "Rawang Echoes of the Mountains",
      ownerType: "singer",
      durationSeconds: 185,
      audioUrl: "synth:260:350",
      lyrics: "[Rawang]\nYupa yupa, zi nung ka,\nAnu ka ring, zong so.\n\n[English Translation]\nSleep peacefully little child,\nProtected by mother's ancient love.",
      genre: "Traditional Lullaby",
    },
    // Album 2 (Singer: Seng Rawang) — index 1
    {
      albumIndex: 1,
      title: "Highland Spring Festival",
      rawangTitle: "Manau Poi Lagung",
      artistName: "Seng Rawang",
      albumName: "Golden Highland Melodies",
      ownerType: "singer",
      durationSeconds: 210,
      audioUrl: "synth:520:680",
      lyrics: "[Rawang]\nManau poi rung, zi mu ma,\nGoli so ring, Rawang ka.\n\n[English Translation]\nDance together at the Highland festival,\nJoy fills our ancestral hills.",
      genre: "Festive Folk",
      hasKaraoke: true,
      karaokeAudioUrl: "synth:karaoke:520:680",
    },
    {
      albumIndex: 1,
      title: "Voice of Putao",
      rawangTitle: "Putao Hka So",
      artistName: "Seng Rawang",
      albumName: "Golden Highland Melodies",
      ownerType: "singer",
      durationSeconds: 225,
      audioUrl: "synth:480:600",
      lyrics: "[Rawang]\nPutao ma, zi mu ma,\nRawang ka, ring zong so.",
      genre: "Modern Folk",
    },
    {
      albumIndex: 1,
      title: "Dawn Chorus in N'Mai Hka",
      rawangTitle: "N'Mai Hka So Lagung",
      artistName: "Seng Rawang",
      albumName: "Golden Highland Melodies",
      ownerType: "singer",
      durationSeconds: 190,
      audioUrl: "synth:350:500",
      lyrics: "[Rawang Traditional Dawn Song]",
      genre: "Acoustic",
    },
    // Album 3 (Organization: RLCA) — index 2
    {
      albumIndex: 2,
      title: "Traditional Courtship Chant",
      rawangTitle: "Shingla Kadu So",
      artistName: "RLCA Elders",
      albumName: "Rawang Heritage Archive Vol. 1",
      ownerType: "organization",
      durationSeconds: 310,
      audioUrl: "synth:300:420",
      lyrics: "[Rawang]\nShingla kadu, zong zi ma,\nRawang ka ring, ka ma.\n\n[English Translation]\nRecorded by the Cultural Association for heritage preservation.",
      genre: "Heritage Archive",
    },
    {
      albumIndex: 2,
      title: "Elders' Wisdom Chant",
      rawangTitle: "Dawa So Lagung",
      artistName: "RLCA Elders",
      albumName: "Rawang Heritage Archive Vol. 1",
      ownerType: "organization",
      durationSeconds: 280,
      audioUrl: "synth:280:390",
      lyrics: "[Heritage Field Recording]",
      genre: "Cultural Lore",
    },
    {
      albumIndex: 2,
      title: "New Year Unity Anthem",
      rawangTitle: "Rawang Num Poi",
      artistName: "Rawang Cultural Ensemble",
      albumName: "Rawang Heritage Archive Vol. 1",
      ownerType: "organization",
      durationSeconds: 250,
      audioUrl: "synth:440:580",
      lyrics: "[Unity Cultural Choir]",
      genre: "Anthem",
    },
    {
      albumIndex: 2,
      title: "Plow & Soil Blessing",
      rawangTitle: "Pung Lagung Blessing",
      artistName: "RLCA Heritage Group",
      albumName: "Rawang Heritage Archive Vol. 1",
      ownerType: "organization",
      durationSeconds: 230,
      audioUrl: "synth:310:430",
      lyrics: "[Agricultural Blessing Chant]",
      genre: "Ritual Chant",
    },
    // Album 4 (Organization: Rawang Youth Heritage Choir) — index 3
    { albumIndex: 3, title: "Mountains Rejoice Choir", rawangTitle: "Razi Lagung Choir", artistName: "Rawang Youth Choir", albumName: "Northern Valley Choral Hymns", ownerType: "organization", durationSeconds: 245, audioUrl: "synth:400:550", lyrics: "[Four-Part Rawang Polyphonic Harmony]", genre: "Choral Hymn" },
    { albumIndex: 3, title: "Grace Over Valley", rawangTitle: "Hka Wang Grace", artistName: "Rawang Youth Choir", albumName: "Northern Valley Choral Hymns", ownerType: "organization", durationSeconds: 210, audioUrl: "synth:360:480", lyrics: "[Sacred Gospel Harmony]", genre: "Choral Hymn" },
    // Album 5 (Anonymous) — index 4
    { albumIndex: 4, title: "Ancient Pine Ridge Ritual", rawangTitle: "Pungye Ritual Chant", artistName: "Traditional Ancestors", albumName: "Ancient River Chants & Rituals", ownerType: "anonymous", durationSeconds: 295, audioUrl: "synth:220:330", lyrics: "[Ancient Oral Tradition Passed Through Generations]", genre: "Ritual Chant" },
    { albumIndex: 4, title: "Solitary Hunter's Echo", rawangTitle: "Hkamti Echo", artistName: "Highland Nomads", albumName: "Ancient River Chants & Rituals", ownerType: "anonymous", durationSeconds: 205, audioUrl: "synth:250:370", lyrics: "[Highland Echo Call]", genre: "Traditional Call" },
    // Album 6 (Anonymous) — index 5
    { albumIndex: 5, title: "Pung-Lu Bamboo Flute Melody", rawangTitle: "Pung-Lu Solos", artistName: "Anonymous Bamboo Master", albumName: "Bamboo Harp & Flute Solos", ownerType: "anonymous", durationSeconds: 260, audioUrl: "synth:520:700", lyrics: "[Instrumental Bamboo Flute Performance]", genre: "Instrumental Solo" },
    { albumIndex: 5, title: "Rawang Mouth Harp Echoes", rawangTitle: "Goli Mouth Harp", artistName: "Anonymous Highland Musician", albumName: "Bamboo Harp & Flute Solos", ownerType: "anonymous", durationSeconds: 175, audioUrl: "synth:600:800", lyrics: "[Instrumental Mouth Harp]", genre: "Instrumental Solo" },
    // Dummy albums 7–11 onwards follow same pattern (1 track each)
    { albumIndex: 6, title: "Highland Morning", rawangTitle: "Dingsa Wang Rung", artistName: "John Singer", albumName: "John's Acoustic Hits", ownerType: "singer", durationSeconds: 203, audioUrl: "synth:320:480", lyrics: "[Details...]", genre: "Folk Ballad" },
    { albumIndex: 7, title: "Bamboo Wind Song", rawangTitle: "Pung Lung Rung", artistName: "Maria Artist", albumName: "Maria's Folk Songs", ownerType: "singer", durationSeconds: 195, audioUrl: "synth:440:620", lyrics: "[Details...]", genre: "Folk Ballad", hasKaraoke: true, karaokeAudioUrl: "synth:karaoke:440:620" },
    { albumIndex: 8, title: "Echo of the Peaks", rawangTitle: "Hkakabo Larwi So", artistName: "David Vocals", albumName: "David Unplugged", ownerType: "singer", durationSeconds: 230, audioUrl: "synth:460:640", lyrics: "[Details...]", genre: "Acoustic Ballad" },
    { albumIndex: 9, title: "Singing By the Stream", rawangTitle: "Hka Rung Zong", artistName: "Sarah Melody", albumName: "Sarah's Classic Melodies", ownerType: "singer", durationSeconds: 210, audioUrl: "synth:480:660", lyrics: "[Details...]", genre: "Folk Ballad", hasKaraoke: true, karaokeAudioUrl: "synth:karaoke:480:660" },
    { albumIndex: 10, title: "Starlight Over Nmai", rawangTitle: "Larwi Nmai So", artistName: "Peter Tune", albumName: "Peter's Evening Tunes", ownerType: "singer", durationSeconds: 218, audioUrl: "synth:370:530", lyrics: "[Details...]", genre: "Acoustic Ballad" },
    { albumIndex: 11, title: "Collective Harvest Hymn", rawangTitle: "Rung Lagung Zong", artistName: "Traditional Arts Ensemble", albumName: "Traditional Arts Compilation", ownerType: "organization", durationSeconds: 238, audioUrl: "synth:450:630", lyrics: "[Details...]", genre: "Choral Traditional" },
  ],

  playlists: [],

  chatMessages: [
    {
      senderName: "Ah Dang (Putao)",
      message: "Shingla kadoo! Welcome to the Rawang Music preservation platform!",
      timestamp: Date.now() - 86400000 * 2,
      isUser: false,
    },
    {
      senderName: "Seng Hkawn (Myitkyina)",
      message: "I am so happy to see old traditional bamboo flute songs preserved here! Check out 'Pungye Harvest Song'!",
      timestamp: Date.now() - 86400000,
      attachedTrackTitle: "Pungye Harvest Song",
      trackSearchBy: "title", // will resolve to actual trackId in seed.js
      isUser: false,
    },
    {
      senderName: "Mung Rawang",
      message: "Downloading songs for offline listening is so helpful when travelling to northern mountain villages without internet.",
      timestamp: Date.now() - 3600000 * 4,
      isUser: false,
    },
  ],
};

module.exports = seedData;
